// PWA wiring (WS-H): the web app manifest, the service-worker source (with its
// config injected so one deploy = one new SW), and the offline fallback page.
//
// The service worker itself lives in client/sw.js and is served from the site
// root — a worker's *scope* is capped by the path it is served from, so it
// must be "/sw.js", not "/client/sw.js".
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ASSET_VERSION, card } from "./html.ts";

/** Bumped implicitly by ASSET_VERSION: a CSS/JS change renames the cache. */
export const SHELL_CACHE = `looplab-shell-${ASSET_VERSION}`;

/** Precached on install — the frame of the app, not its data. */
export const SHELL_ASSETS = [
  "/",
  "/offline",
  `/style.css?v=${ASSET_VERSION}`,
  "/icons/icon-192.png",
];

/**
 * Paths that must NEVER be served from a shared cache: they are per-user
 * (accounts, downloads) or must be live (the health probe). A stale cached
 * /account on a shared device is a privacy failure, not a performance win.
 */
export const NEVER_CACHE_PREFIXES = [
  "/account",
  "/auth/",
  "/signin",
  "/signup",
  "/reset",
  "/verify/",
  "/unsubscribe/",
  "/export/",
  "/webhooks/",
  "/health",
  "/api/push/",
];

/** Network-first: correctness beats speed for anything race-related. */
export const NETWORK_FIRST_PREFIXES = ["/data/", "/api/", "/live", "/predictions", "/dfs"];

/**
 * The complete icon set, generated by `bun run gen:icons`. Routes serve from
 * this allowlist rather than interpolating a request path into a filename —
 * that keeps a missing icon a clean 404 (Bun.file throws at read time, which
 * would otherwise surface as a 500) and puts no user input near the filesystem.
 */
export const PWA_ICONS = [
  "icon-192.png",
  "icon-512.png",
  "icon-maskable-512.png",
  "apple-touch-icon.png",
] as const;

export interface ManifestOptions {
  /** Product name — placeholder until D2 lands the real one. */
  name?: string;
  shortName?: string;
}

export function webManifest(opts: ManifestOptions = {}): Record<string, unknown> {
  return {
    name: opts.name ?? "Looplab — NASCAR loop-data analytics",
    short_name: opts.shortName ?? "Looplab",
    description:
      "NASCAR loop data, proprietary metrics, race predictions and DFS projections — built for people who want the numbers behind the result.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0a0c10",
    theme_color: "#0a0c10",
    categories: ["sports", "news"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // A maskable icon keeps the mark inside the launcher's safe zone instead
      // of letting Android crop the artwork into a circle.
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}

const SW_SOURCE_URL = new URL("./client/sw.js", import.meta.url);

/** The service worker with its build-time config substituted in. */
export function serviceWorkerSource(liveOrigin: string): string {
  const source = readFileSync(fileURLToPath(SW_SOURCE_URL), "utf8");
  const config = {
    version: ASSET_VERSION,
    cache: SHELL_CACHE,
    shell: SHELL_ASSETS,
    neverCache: NEVER_CACHE_PREFIXES,
    networkFirst: NETWORK_FIRST_PREFIXES,
    liveOrigin,
    offlineUrl: "/offline",
  };
  return source.replace("__SW_CONFIG__", JSON.stringify(config));
}

export function offlineContent(): string {
  return card(
    "You're offline",
    `<p class="note">This page isn't in your device's cache yet. Race data needs a connection —
reconnect and it'll load.</p>
<p class="note">Pages you've already visited stay available offline, and anything you had open
keeps working.</p>
<p class="note" style="margin-top:10px"><a href="/">← Try the home page</a></p>`,
  );
}

/**
 * Install affordance (revealed by /install.js only when the browser offers
 * an install prompt, or on iOS Safari where the prompt event doesn't exist).
 */
export function installBanner(): string {
  return `<div class="card install-card" id="install-card" hidden>
  <div class="card-h"><h2>Install Looplab</h2></div>
  <p class="note" id="install-copy">Add it to your home screen for full-screen race-day access.</p>
  <p style="margin-top:8px"><button class="install-btn" id="install-go" type="button">Install</button>
  <button class="install-dismiss" id="install-no" type="button">Not now</button></p>
</div>`;
}
